version: '3.4'

networks:
  E_Academy_Network: 


services:
  e_academy_database:
    container_name: "E_Academy_DB"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345
    networks:
      - E_Academy_Network
  e_academy_backend:
    container_name: "E_Academy_API"
    image: ${DOCKER_REGISTRY-}eacademybackend
    build:
      context: .
      dockerfile: E_Academy_Backend/Dockerfile
    ports:
      - 8001:8080
    depends_on:
      - e_academy_database
    environment:
      - DB_HOST=e_academy_database
      - DB_NAME=E_Academy
      - DB_SA_PASSWORD=password@12345
    networks:
      - E_Academy_Network
